M48
; DRILL file {KiCad 9.0.3-9.0.3-0~ubuntu24.04.1} date 2025-10-28T12:02:59-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-28T12:02:59-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3-9.0.3-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.500
%
G90
G05
T1
X113.432Y71.562
X113.432Y65.782
T2
X3.92Y66.61
X3.92Y17.46
X90.0Y66.61
X105.99Y17.46
T3
X63.4Y6.0
X102.9Y6.0
M30
